### ISSUE TITLE
AttributeError: module 'verde' has no attribute 'Linear'

### ISSUE THREAD

**Issue by ianpdavies** [fatiando/verde#402]
Using the latest release of `verde` 1.7.0

I am trying to follow the example code here
https://www.fatiando.org/verde/dev/gallery/linear_gridder.html?highlight=linear

but am unable to use the linear interpolator class

```
import verde as vd
vd.Linear()
```

```
Traceback (most recent call last):
  File "/Users/myusername/opt/miniconda3/envs/dev/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-e6534d0ba5c9>", line 1, in <module>
    vd.Linear()
AttributeError: module 'verde' has no attribute 'Linear'
```

None of the other interpolator classes besides `Spline` and `SplineCV` appear to be usable, and are not in the `verde` directory
https://github.com/fatiando/verde/tree/main/verde

Is this feature simply not usable yet in the current release, or is this an install or usage problem on my end?

Thank you

**Comment by santisoler** [comment]
Hi @ianpdavies. Thanks for opening this issue!

The `verde.Linear` class was introduced in https://github.com/fatiando/verde/pull/372, while the latest release of Verde (v1.7.0) dates from March 25, 2022. So this class is not yet available on any release of Verde. What you are looking at is at the documentation of the latest **development** version of Verde and not to the one for the latest release. Check that you have a `dev` in that url, while the links for the latest release have a `latest` instead, like this: https://www.fatiando.org/verde/latest/

If you really want to use the `Linear` class you can wait until we make a new release of Verde (we really should do it soon!) or you can install the development version of Verde by cloning the repository and manually installing it (you can follow some portion of the [Contributing Guidelines](https://github.com/fatiando/community/blob/main/CONTRIBUTING.md#setting-up-your-environment) to do so), or using `pip` and pointing to the url of the repo:

```
pip install git+https://www.github.com/fatiando/verde
```

Hope this helps! Let me know how it goes and if you manage to solve it, feel free to close this issue.

**Comment by leouieda** [comment]
Closing this since it's an install issue. Feel free to reopen if it keeps coming up after the upgrade.
